### ISSUE TITLE
systemData

### ISSUE THREAD

**Issue by pr0dukt** [exelix11/SwitchThemeInjector#17]
Where does the systemData folder go on the SD to be recognized by the homebrew? It's driving me crazy. I have put the folder with every .szs file in it, into several locations, since I can't get the auto home menu extraction method to work from the app itself without crashing my switch.

So please just tell me where i need to place this folder. This app used to work perfectly and have had several custom themes installed on my switch already, but since the last couple updates, All I get is bullshit messages telling me it's missing .szs files, when they are in like 4 different locations on my SD, or I get black screen error crashes when trying to extract the systemData folder from the app, despite having the files already.
It's driving me up the wall, any assistance would be much obliged.

**Comment by exelix11** [comment]
`systemData` should be in the `themes` folder, make sure to match the case.
if the app crashes during the extraction it's likely that your key file is messed up or your sd is corrupted (it happens if you use an exfat sd).
If you got the keys from the internet there is a website with some "not confirmed" keys, delete them if you downloaded that. If you're using lockpick make sure to delete all `prod.keys` from the sd before dumping the keys.
If your sd card is corrupted you may encounter more crashes later on.
On version 1.2 you can still follow the old dumping process by pressing L + R when dumping the home menu, this will just dump the nca but not extract it.

**Comment by pr0dukt** [comment]
I got it, it was indeed the unconfirmed keys that were hanging me up, I hadn't noticed those had gotten added since the last time I updated my keys file from a certain course, since I run on Emunand. Anyways, Thanks alot for the asist. Finally working the way it used to.

**Comment by exelix11** [comment]
👍
