### ISSUE TITLE
Firmware 9.1.0 is not supported

### ISSUE THREAD

**Issue by danfozzy** [exelix11/SwitchThemeInjector#42]
As title, it seems the latest fw update causes crashes if a theme is installed on both atmos. 10.0 and the latest sxos.

**Comment by exelix11** [comment]
It does. As i already explained on discord, a fix is on its way.
Atmosphere support requires some changes due to the fact that the fsmitm folder was changed in 0.10.0. 
Sxos should work fine with latest release as long as you don't install lockscreen themes, for sx this will not be fixed as the cfw doesn't support patching titles via ips files.

**Comment by rashevskyv** [comment]
It works fine on 0.10 too, cause 0.10 automatically moves all folders in `titles` to `content`. Exept lockscreen theme obviously

**Comment by exelix11** [comment]
But when you install a new theme the installer will use the titles folder and as atmosphere already has the contents dir won't copy the new files. This also means uninstall theme won't work.

**Comment by rashevskyv** [comment]
Yep, but after reboot, atmosphere moves content of `titles` to `content` automatically. Uninstallation will not work fo sure.

**Comment by exelix11** [comment]
Update with 9.1.0 and content folder support is out.
https://github.com/exelix11/SwitchThemeInjector/releases
