### ISSUE TITLE
is there a hydrated default layout template json available?

### ISSUE THREAD

**Issue by miltoncandelero** [exelix11/SwitchThemeInjector#6]
I was thinking about making a ""parser"" for the json layouts (a simple way of previewing that that layout will look like and in the future maybe some sort of visual editor).

An json file of the unmodified home menu completely hydrated (with the values for size, scale, rotation, pos, and the such) would be really useful to know where and what size to draw elements.

(My B plan is to load a scz, change all the values by 1, create the diff json, offset the values to their original value. But maybe you have a clean dump already)

Thanks!

**Comment by exelix11** [comment]
I don't have it nor will i make it, for the simple reason that the point of json layouts is to avoid sharing copyrighted bflyt files, either original or modified, encoding a whole bflyt as json would legally put it into a gray area, this is why json layouts only contain the "most important" properties, they can't be used to rebuild a layout from scratch.
If you want to make an editor for layouts you should work directly on the bflyt format, you can start by checking out my [class](https://github.com/exelix11/SwitchThemeInjector/blob/master/SwitchThemesCommon/Bflyt.cs) for handling it and reading the documentation on [this wiki](http://mk8.tockdom.com/wiki/BFLYT_(File_Format)), since all the parsing and saving is already done you may want to focus your attention on the [pan1 format](http://mk8.tockdom.com/wiki/BFLYT_(File_Format)#pan1).
