### ISSUE TITLE
Suggestion: Support for animated/video backgrounds and background music

### ISSUE THREAD

**Issue by LillianGoulston** [exelix11/SwitchThemeInjector#68]
What are the obstacles to implementing animated backgrounds like on PS4 (made up of static images which then have instructions for movement, like scrolling across the screen) or video backgrounds like Wallpaper Engine (basically .mp4 files)? Is this even possible?

Also, what are the obstacles to implementing background music? I know sysmodules like sys-tune exist, but there's no support for limiting it based on titleID. A now-defunct sysmodule did that (sys-audioplayer), but it hasn't been updated since 9.0.0.

**Comment by exelix11** [comment]
Switch themes are a ugly hack that patches the home menu layouts to display custom images, that means we're limited to the capabilities of the home menu's layout engine.
It's quite powerful don't get me wrong but videos are totally out of question.
Same holds true for music, the home menu doesn't have any code to play music so, at least with my method, there's no way to add background music.
Would it be possible to have multiple static images moving ? In theory yes, layouts have a fairly complete animations support that allows changing position, rotation -even in 3d space-, visibility and so on, there are a few problems: 
- Not everything about animations is known, eg some triggers seem to be hardcoded so there may be limits to what it can be done.
- Memory: the home menu runs quite thightly on ram and idk how many images you can add without getting crashes, it would be a tedious trial and error process and could break at any point with updates.
Current themes fall within a limit on resource size set by Nintendo, except for lock screen that's why the patch is needed, I like to stay within that space as I believe it shouldn't change too much with updates meaning themes will work unchanged on many firmwares.
- firmware compatibility: the nxtheme format attempts to solve the firmware compatibility problem by abstracting the patching part away, with more invasive patches like adding new panes, extra images and animations idk if it will be possible to keep compatibility. And i wouldn't like people going back to szs sharing.
- Finally, a personal note: I kinda lost interest in experimenting with themes given how annoying the testing process is, I accomplished what I set out to do and doubt will experiment more on my own, I will still support this app with updates and compatibility but don't have plans for major features, at least not on my own, contributions are always welcome.

Closing this as I think I answered all your questions, if there's anything more follow up here.

**Comment by LillianGoulston** [comment]
Thanks for the response. I hope animations get figured out eventually.
