### ISSUE TITLE
gui problem

### ISSUE THREAD

**Issue by tomoya1230** [exelix11/SwitchThemeInjector#74]
After selecting an image and pressing the build button, a screen to decide the name appears, but I can not proceed from there

Also, regarding the functions that can be used online 
Select an image and press the build button, but it says that the format is not supported
I chose .jpg

**Comment by exelix11** [comment]
> After selecting an image and pressing the build button, a screen to decide the name appears, but I can not proceed from there

This is most likely because you have custom DPI set in windows, thought this bug was solved. As a workaround you should be able to set normal dpi in the application compatibility property. 
Otherwise you can press the tab button while the author name textbox is selected, that will move the cursor to the OK button that's out of the view then you can confirm by pressing return.

>  Select an image and press the build button, but it says that the format is not supported

Jpeg images can be encoded in different ways, when they're encoded as progressive they're not supported, the solution is to disable the progressive option in your image editor, eg in photoshop when saving there's a button for advanced settings where it lets you uncheck progressive jpg

**Comment by tomoya1230** [comment]
Succeeded. Thank you very much
