### ISSUE TITLE
12.0.0 Atmosphere Not Working 

### ISSUE THREAD

**Issue by Zero9887** [exelix11/SwitchThemeInjector#83]
I downloaded some themes and tried to apply them using this app and for some reason every time I reboot my console the themes don't apply themselves.

**Comment by Dboard52** [comment]
Experiencing the same issue aswell

**Comment by exelix11** [comment]
This seems to be because atmosphere removed the contents folder so the theme installer assumes you're on an old version of atmosphere and creates one called titles, which won't work.

To fix this i dropped titles support on atmosphere with latest commit, a test build should be ready in a few minutes [here](https://github.com/exelix11/SwitchThemeInjector/runs/2322229242). Let me know if it works

**Comment by exelix11** [comment]
There was a problem with outdated libnx on my machine and the build failed, fixed the issue, [this version](https://github.com/exelix11/SwitchThemeInjector/suites/2473713444/artifacts/53207322) should work fine on latest atmosphere

**Comment by exelix11** [comment]
[Latest release](https://github.com/exelix11/SwitchThemeInjector/releases/latest) should fix this issue
