### ISSUE TITLE
Atmosphère 1.0.0 not compatible

### ISSUE THREAD

**Issue by YazZHh** [exelix11/SwitchThemeInjector#95]
- Firmware 12.1.0
- Atmosphère 1.0.0 (with latest sigpatches)

When I launch the homebrew, it says **"Key extraction from FS failed !"**, then **"Keys have not been initialized"**
And when I'm finally in the main menu, it gives me details of the error :

![2021090916444100-2A84157C8F615AF1939F33CA6D6E18E9](https://user-images.githubusercontent.com/88186277/132709948-c3ee3c11-d775-4851-b8ad-06639a961b86.jpg)

**Comment by exelix11** [comment]
I'm currently busy and couldn't test myself but another user just confirmed it's working fine, plus since ams 1.0 released there haven't been any other reports related to this which leads me to believe your setup may be broken in some way.
Can you try setting up atmosphere and the theme installer from scratch ? Even on a different sd card is fine.

**Comment by YazZHh** [comment]
Well, I've fixed the issue by extracting 2 times the home menu. It' wasn't working the first time and I don't know why, but yeah I can confirm that it's working on Atmosphère 1.0.0
